-- SKALLP Payment PostgreSQL Full Database Export
-- Generated for AWS Server Import

-- Data for branches
INSERT INTO branches (id, code, name, state, created_at, is_active) VALUES (1, 'RAI', 'Raipur Head Office', 'Chhattisgarh', '"2026-08-11T06:02:41.121Z"', true) ON CONFLICT DO NOTHING;
INSERT INTO branches (id, code, name, state, created_at, is_active) VALUES (2, 'RGH', 'Raigarh Plant & Sponge Iron Division', 'Chhattisgarh', '"2026-08-11T06:02:41.121Z"', true) ON CONFLICT DO NOTHING;
INSERT INTO branches (id, code, name, state, created_at, is_active) VALUES (3, 'KAN', 'Kanker Iron Ore Mines & Site Office', 'Chhattisgarh', '"2026-08-11T06:02:41.121Z"', true) ON CONFLICT DO NOTHING;
INSERT INTO branches (id, code, name, state, created_at, is_active) VALUES (5, 'DUR', 'Durg Steel Division', 'Chhattisgarh', '"2026-08-11T08:19:35.303Z"', true) ON CONFLICT DO NOTHING;

-- Data for projects
INSERT INTO projects (id, code, name, branch_id, created_at, is_active) VALUES (2, 'PRJ-BILLET-01', 'Steel Billet Continuous Casting Plant', 2, '"2026-08-11T06:02:41.124Z"', true) ON CONFLICT DO NOTHING;
INSERT INTO projects (id, code, name, branch_id, created_at, is_active) VALUES (3, 'PRJ-SOLAR-01', '15 MW Captive Solar Power Project', 3, '"2026-08-11T06:02:41.124Z"', true) ON CONFLICT DO NOTHING;
INSERT INTO projects (id, code, name, branch_id, created_at, is_active) VALUES (4, 'PRJ-RWS-03', 'Railway Siding & Logistics Yard Phase 3', 1, '"2026-08-11T06:02:41.124Z"', true) ON CONFLICT DO NOTHING;
INSERT INTO projects (id, code, name, branch_id, created_at, is_active) VALUES (1, 'PRJ-SPONGE-02', 'Sponge Iron Expansion Unit 2', 2, '"2026-08-11T06:02:41.124Z"', false) ON CONFLICT DO NOTHING;

-- Data for users
INSERT INTO users (id, name, email, password_hash, role, branch_id, project_id, mobile, is_active, created_at, updated_at) VALUES (3, 'Kushal Rathod', 'kushal@skallp.in', '$2a$10$rOBivOBR7u6ZXVGEIIWunucDCoIRgnTN1OvIFcV93tRxNy2L36V32', 'purchase_officer', 1, 1, '9874563210', true, '"2026-08-11T06:42:20.978Z"', '"2026-08-11T06:42:20.978Z"') ON CONFLICT DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, branch_id, project_id, mobile, is_active, created_at, updated_at) VALUES (4, 'Priti Dewangan', 'preeti@skallp.in', '$2a$10$rOBivOBR7u6ZXVGEIIWunucDCoIRgnTN1OvIFcV93tRxNy2L36V32', 'ho_verifier', 1, 2, '9874563210', true, '"2026-08-11T11:17:50.363Z"', '"2026-08-11T11:17:50.363Z"') ON CONFLICT DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, branch_id, project_id, mobile, is_active, created_at, updated_at) VALUES (5, 'Tuleshwar Kumar', 'tulesh@skallp.in', '$2a$10$rOBivOBR7u6ZXVGEIIWunucDCoIRgnTN1OvIFcV93tRxNy2L36V32', 'ca', NULL, 1, '9874563210', true, '"2026-08-13T10:08:57.683Z"', '"2026-08-13T10:08:57.683Z"') ON CONFLICT DO NOTHING;
INSERT INTO users (id, name, email, password_hash, role, branch_id, project_id, mobile, is_active, created_at, updated_at) VALUES (1, 'System Administrator', 'admin@skallp.in', '$2a$10$rOBivOBR7u6ZXVGEIIWunucDCoIRgnTN1OvIFcV93tRxNy2L36V32', 'admin', NULL, NULL, '+91 98261 99999', true, '"2026-08-11T06:02:41.213Z"', '"2026-08-13T10:09:12.262Z"') ON CONFLICT DO NOTHING;

-- Data for vendors
INSERT INTO vendors (id, vendor_code, legal_name, trade_name, pan, gstin, msme_status, address, contact_person, mobile, email, bank_name, beneficiary_name, bank_account_number, ifsc, vendor_category, is_active, bank_details_authorized, bank_authorized_by, bank_authorized_at, created_at, updated_at, status, created_by_user_id, ho_verification_remarks, ho_verified_by, ho_verified_at, ca_approved_by, ca_approved_at, ca_remarks) VALUES (2, 'VEN-96385', 'Botivate Services Llp', 'Botivate', 'AAABBB2656A', '22AAA2312AW12', 'exempted', 'Shri Ram Business Park Saddu.', 'Pratap Verma', '9874563210', 'botivate@gmail.com', 'HDFC Bank', 'Pratap Verma', '78964303210', 'HDFC001122', 'Services', true, false, NULL, NULL, '"2026-08-13T09:21:48.649Z"', '"2026-08-13T09:21:48.649Z"', 'approved', NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO vendors (id, vendor_code, legal_name, trade_name, pan, gstin, msme_status, address, contact_person, mobile, email, bank_name, beneficiary_name, bank_account_number, ifsc, vendor_category, is_active, bank_details_authorized, bank_authorized_by, bank_authorized_at, created_at, updated_at, status, created_by_user_id, ho_verification_remarks, ho_verified_by, ho_verified_at, ca_approved_by, ca_approved_at, ca_remarks) VALUES (4, 'VEN-TEST-878', 'Test Steel Supplier Pvt Ltd', 'Test Steel', 'AAACS5272A', '22AAACS5272A1Z4', 'small', 'Raigarh Industrial Estate', 'Rajesh Sharma', '9876543210', 'rajesh@teststeel.com', 'State Bank of India', 'Test Steel Supplier Pvt Ltd', '30495839201', 'SBIN0001234', 'Raw Material', true, true, NULL, NULL, '"2026-08-13T09:34:02.833Z"', '"2026-08-13T09:34:02.838Z"', 'approved', 3, 'Verified physical GST copy and bank cancelled cheque. OK.', 4, '"2026-08-13T09:34:02.836Z"', 1, '"2026-08-13T09:34:02.838Z"', NULL) ON CONFLICT DO NOTHING;
INSERT INTO vendors (id, vendor_code, legal_name, trade_name, pan, gstin, msme_status, address, contact_person, mobile, email, bank_name, beneficiary_name, bank_account_number, ifsc, vendor_category, is_active, bank_details_authorized, bank_authorized_by, bank_authorized_at, created_at, updated_at, status, created_by_user_id, ho_verification_remarks, ho_verified_by, ho_verified_at, ca_approved_by, ca_approved_at, ca_remarks) VALUES (3, 'VEN-TEST-426', 'Test Steel Supplier Pvt Ltd', 'Test Steel', 'AAACS7601A', '22AAACS7601A1Z9', 'small', 'Raigarh Industrial Estate', 'Rajesh Sharma', '9876543210', 'rajesh@teststeel.com', 'State Bank of India', 'Test Steel Supplier Pvt Ltd', '30495839201', 'SBIN0001234', 'Raw Material', true, true, NULL, NULL, '"2026-08-13T09:29:32.882Z"', '"2026-08-13T10:11:14.049Z"', 'approved', 1, 'ok but crosscheck bank details.', 4, '"2026-08-13T10:07:32.127Z"', 5, '"2026-08-13T10:11:14.049Z"', NULL) ON CONFLICT DO NOTHING;
INSERT INTO vendors (id, vendor_code, legal_name, trade_name, pan, gstin, msme_status, address, contact_person, mobile, email, bank_name, beneficiary_name, bank_account_number, ifsc, vendor_category, is_active, bank_details_authorized, bank_authorized_by, bank_authorized_at, created_at, updated_at, status, created_by_user_id, ho_verification_remarks, ho_verified_by, ho_verified_at, ca_approved_by, ca_approved_at, ca_remarks) VALUES (5, 'VEN-47155', 'Zora The Mall', 'Zora Mall', 'ZZZOOORRR11', 'MMMAAALLL001', 'exempted', 'Zora The Mall Serikhedi', 'Zorawar SIngh Mall', '9638527410', 'zorawar@gmail.com', 'IDB Bank', 'Zorawar Singh', '987456321123', 'ZRWR963258', 'Logistics', true, true, NULL, NULL, '"2026-08-14T06:11:10.589Z"', '"2026-08-14T06:14:22.027Z"', 'approved', 3, 'all ok', 4, '"2026-08-14T06:12:56.199Z"', 5, '"2026-08-14T06:14:22.027Z"', NULL) ON CONFLICT DO NOTHING;
INSERT INTO vendors (id, vendor_code, legal_name, trade_name, pan, gstin, msme_status, address, contact_person, mobile, email, bank_name, beneficiary_name, bank_account_number, ifsc, vendor_category, is_active, bank_details_authorized, bank_authorized_by, bank_authorized_at, created_at, updated_at, status, created_by_user_id, ho_verification_remarks, ho_verified_by, ho_verified_at, ca_approved_by, ca_approved_at, ca_remarks) VALUES (6, 'VEN-71042', 'Magneto The Mall', 'Magneto', 'MGNT5263O', 'MGNT852963741', 'exempted', 'Magneto The Mall ', 'Magneto Singh', '9638527410', 'magnet@gmail.com', 'KOTAK BANK', 'Magneto', '9638527410', 'MG852963', 'Logistics', true, true, NULL, NULL, '"2026-08-14T06:22:55.528Z"', '"2026-08-14T07:06:56.850Z"', 'approved', 3, 'ok', 4, '"2026-08-14T07:06:22.437Z"', 5, '"2026-08-14T07:06:56.850Z"', NULL) ON CONFLICT DO NOTHING;

-- Data for bills
INSERT INTO bills (id, internal_bill_id, branch_id, project_id, vendor_id, bill_type, invoice_number, invoice_date, invoice_amount, gst_amount, net_bill_amount, po_wo_number, material_service_desc, due_date, bill_category, remarks, status, total_paid_amount, balance_payable, is_duplicate_override, duplicate_override_reason, linked_proforma_bill_id, created_by_user_id, created_at, updated_at, eway_bill_number) VALUES (2, 'RAI/26-27/TEST125', 1, 1, 4, 'tax_invoice', 'INV-TEST-242', '"2026-08-12T18:30:00.000Z"', '150000.00', '27000.00', '177000.00', NULL, 'Test Steel Plates', NULL, NULL, NULL, 'paid', '177000.00', '0.00', false, NULL, NULL, 3, '"2026-08-13T10:30:42.261Z"', '"2026-08-13T12:08:52.189Z"', NULL) ON CONFLICT DO NOTHING;
INSERT INTO bills (id, internal_bill_id, branch_id, project_id, vendor_id, bill_type, invoice_number, invoice_date, invoice_amount, gst_amount, net_bill_amount, po_wo_number, material_service_desc, due_date, bill_category, remarks, status, total_paid_amount, balance_payable, is_duplicate_override, duplicate_override_reason, linked_proforma_bill_id, created_by_user_id, created_at, updated_at, eway_bill_number) VALUES (3, 'RAI/26-27/998811', 1, 1, 2, 'tax_invoice', 'INV-TEST-9988', '"2026-08-12T18:30:00.000Z"', '100000.00', '18000.00', '118000.00', 'PO-2026-001', 'Test TMT Steel Bars', '"2026-08-29T18:30:00.000Z"', 'Raw Material', 'Test bill creation', 'paid', '118000.00', '0.00', false, NULL, NULL, 3, '"2026-08-13T12:17:59.915Z"', '"2026-08-14T05:34:51.741Z"', '201928472918') ON CONFLICT DO NOTHING;
INSERT INTO bills (id, internal_bill_id, branch_id, project_id, vendor_id, bill_type, invoice_number, invoice_date, invoice_amount, gst_amount, net_bill_amount, po_wo_number, material_service_desc, due_date, bill_category, remarks, status, total_paid_amount, balance_payable, is_duplicate_override, duplicate_override_reason, linked_proforma_bill_id, created_by_user_id, created_at, updated_at, eway_bill_number) VALUES (4, 'KAN/26-27/838084', 3, 3, 2, 'reimbursement_expense', 'ertyuio', '"2026-08-12T18:30:00.000Z"', '1500.00', '120.00', '1620.00', 'sdfghjkl', 'ghj', '"2026-08-19T18:30:00.000Z"', 'Raw Material', 'hj', 'paid', '4860.00', '0.00', false, NULL, NULL, 3, '"2026-08-13T12:19:15.379Z"', '"2026-08-14T05:38:07.719Z"', NULL) ON CONFLICT DO NOTHING;

-- Data for bill_documents
INSERT INTO bill_documents (id, bill_id, document_type, file_name, file_path, file_size, mime_type, uploaded_by_user_id, uploaded_at, notes) VALUES (2, 2, 'Query Clarification Document', 'INVO.jpg', '/uploads/documents/QueryDoc_1786620745091_INVO.jpg', '733420', 'image/jpeg', 3, '"2026-08-13T11:32:25.134Z"', 'Uploaded for Query Reply #2') ON CONFLICT DO NOTHING;
INSERT INTO bill_documents (id, bill_id, document_type, file_name, file_path, file_size, mime_type, uploaded_by_user_id, uploaded_at, notes) VALUES (3, 4, 'Invoice Copy', 'INVO.jpg', '/uploads/documents/Invoice_1786623555302_INVO.jpg', '733420', 'image/jpeg', 3, '"2026-08-13T12:19:15.387Z"', 'Uploaded during bill creation') ON CONFLICT DO NOTHING;
INSERT INTO bill_documents (id, bill_id, document_type, file_name, file_path, file_size, mime_type, uploaded_by_user_id, uploaded_at, notes) VALUES (4, 4, 'Invoice Copy', 'IMG_20260810_151828.jpg', '/uploads/documents/Invoice_1786623555314_IMG_20260810_151828.jpg', '3521814', 'image/jpeg', 3, '"2026-08-13T12:19:15.389Z"', 'Uploaded during bill creation') ON CONFLICT DO NOTHING;

-- Data for payment_requests
INSERT INTO payment_requests (id, bill_id, requested_amount, required_payment_date, priority, reason_remarks, verified_amount, status, requested_by_user_id, requested_at, verified_by_user_id, verified_at, verification_notes, updated_at) VALUES (2, 2, '177000.00', '"2026-08-14T18:30:00.000Z"', 'urgent', 'jldi krwao bhia', NULL, 'submitted', 3, '"2026-08-13T11:48:48.345Z"', NULL, NULL, NULL, '"2026-08-13T12:26:41.538Z"') ON CONFLICT DO NOTHING;
INSERT INTO payment_requests (id, bill_id, requested_amount, required_payment_date, priority, reason_remarks, verified_amount, status, requested_by_user_id, requested_at, verified_by_user_id, verified_at, verification_notes, updated_at) VALUES (3, 2, '177000.00', '"2026-08-14T18:30:00.000Z"', 'urgent', 'Direct disbursal request for HO-Approved bill', '1500.00', 'verified', 3, '"2026-08-13T11:51:14.697Z"', 4, '"2026-08-14T05:14:56.096Z"', 'Supporting documents (PO, Invoice, Challan) verified with gate entry. Approved for payment request.', '"2026-08-14T05:14:56.096Z"') ON CONFLICT DO NOTHING;
INSERT INTO payment_requests (id, bill_id, requested_amount, required_payment_date, priority, reason_remarks, verified_amount, status, requested_by_user_id, requested_at, verified_by_user_id, verified_at, verification_notes, updated_at) VALUES (4, 4, '1620.00', '"2026-08-20T18:30:00.000Z"', 'urgent', 'jldi kro', NULL, 'verified', 3, '"2026-08-14T05:21:06.125Z"', NULL, NULL, NULL, '"2026-08-14T05:21:06.125Z"') ON CONFLICT DO NOTHING;
INSERT INTO payment_requests (id, bill_id, requested_amount, required_payment_date, priority, reason_remarks, verified_amount, status, requested_by_user_id, requested_at, verified_by_user_id, verified_at, verification_notes, updated_at) VALUES (5, 3, '118000.00', '"2026-08-19T18:30:00.000Z"', 'critical', 'crititcal', NULL, 'paid', 3, '"2026-08-14T05:21:21.473Z"', NULL, NULL, NULL, '"2026-08-14T05:38:07.722Z"') ON CONFLICT DO NOTHING;

-- Data for ho_queries
INSERT INTO ho_queries (id, bill_id, payment_request_id, query_reason_code, query_text, raised_by_user_id, raised_at, reply_text, replied_by_user_id, replied_at, status) VALUES (2, 2, NULL, 'gst_error', 'GST calculation error in bill. Please upload corrected copy.', 4, '"2026-08-13T10:39:38.567Z"', 'i hav eattached new docs', 3, '"2026-08-13T11:32:25.131Z"', 'replied') ON CONFLICT DO NOTHING;

-- Data for payment_transactions
INSERT INTO payment_transactions (id, bill_id, payment_request_id, payment_amount, payment_date, paying_bank_account, payment_mode, utr_reference_number, payment_remarks, proof_file_name, proof_file_path, paid_by_user_id, paid_at) VALUES (2, 2, NULL, '177000.00', '"2026-08-12T18:30:00.000Z"', 'HDFC Bank - SKAIspat Operations A/C 50200018294019', 'RTGS', 'HDFCR26081300999', 'Test bank release', NULL, NULL, 5, '"2026-08-13T12:08:52.185Z"') ON CONFLICT DO NOTHING;
INSERT INTO payment_transactions (id, bill_id, payment_request_id, payment_amount, payment_date, paying_bank_account, payment_mode, utr_reference_number, payment_remarks, proof_file_name, proof_file_path, paid_by_user_id, paid_at) VALUES (3, 4, NULL, '1620.00', '"2026-08-13T18:30:00.000Z"', 'SBI - SKALLP Project Account (3098...482)', 'IMPS', 'ASDFGHJKRTYUI', 'Bank payment authorized', 'IMG_20260810_151828.jpg', '/uploads/proofs/Proof_IMG_20260810_151828.jpg', 5, '"2026-08-14T05:32:21.312Z"') ON CONFLICT DO NOTHING;
INSERT INTO payment_transactions (id, bill_id, payment_request_id, payment_amount, payment_date, paying_bank_account, payment_mode, utr_reference_number, payment_remarks, proof_file_name, proof_file_path, paid_by_user_id, paid_at) VALUES (4, 3, 5, '118000.00', '"2026-08-13T18:30:00.000Z"', 'SBI - SKALLP Project A/C 30982910482', 'Cheque', 'ERTFYGBHUNJIMK', '', NULL, NULL, 5, '"2026-08-14T05:34:51.675Z"') ON CONFLICT DO NOTHING;
INSERT INTO payment_transactions (id, bill_id, payment_request_id, payment_amount, payment_date, paying_bank_account, payment_mode, utr_reference_number, payment_remarks, proof_file_name, proof_file_path, paid_by_user_id, paid_at) VALUES (5, 4, 5, '1620.00', '"2026-08-13T18:30:00.000Z"', 'SBI - SKALLP Project Account', 'IMPS', 'IMPS202608149999', 'Disbursal executed', NULL, NULL, 5, '"2026-08-14T05:37:51.814Z"') ON CONFLICT DO NOTHING;
INSERT INTO payment_transactions (id, bill_id, payment_request_id, payment_amount, payment_date, paying_bank_account, payment_mode, utr_reference_number, payment_remarks, proof_file_name, proof_file_path, paid_by_user_id, paid_at) VALUES (6, 4, 5, '1620.00', '"2026-08-13T18:30:00.000Z"', 'SBI - SKALLP Project Account', 'IMPS', 'IMPS202608148888', 'Disbursal executed', NULL, NULL, 5, '"2026-08-14T05:38:07.717Z"') ON CONFLICT DO NOTHING;

-- Data for audit_logs
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (1, NULL, 'System', 'system', 'USER_LOGIN', 'user', 1, NULL, NULL, NULL, '{"role":"admin","email":"admin@skallp.in"}', '::1', '"2026-08-11T06:20:49.211Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (2, 1, 'System Administrator', 'admin', 'USER_UPDATED', 'user', 1, NULL, NULL, NULL, '{"name":"System Administrator","role":"admin","email":"admin@skallp.in"}', '::1', '"2026-08-11T06:23:58.272Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (3, NULL, 'System', 'system', 'USER_LOGIN', 'user', 1, NULL, NULL, NULL, '{"role":"admin","email":"admin@skallp.in"}', '::1', '"2026-08-11T06:24:18.058Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (4, 1, 'System Administrator', 'admin', 'USER_CREATED', 'user', 3, NULL, NULL, NULL, '{"name":"Kushal Rathod","role":"purchase_officer","email":"kushal@skallp.in"}', '::1', '"2026-08-11T06:42:20.986Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (5, 1, 'System Administrator', 'admin', 'USER_DEACTIVATED', 'user', 2, NULL, NULL, NULL, '{"email":"test.officer1786430504098@skallp.in","is_active":false}', '::1', '"2026-08-11T06:42:32.508Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (6, 1, 'System Administrator', 'admin', 'USER_ACTIVATED', 'user', 2, NULL, NULL, NULL, '{"email":"test.officer1786430504098@skallp.in","is_active":true}', '::1', '"2026-08-11T06:42:38.499Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (7, NULL, 'System', 'system', 'USER_LOGIN', 'user', 3, NULL, NULL, NULL, '{"role":"purchase_officer","email":"kushal@skallp.in"}', '::1', '"2026-08-11T06:49:58.622Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (8, NULL, 'System', 'system', 'USER_LOGIN', 'user', 1, NULL, NULL, NULL, '{"role":"admin","email":"admin@skallp.in"}', '::1', '"2026-08-11T07:03:53.776Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (9, 1, 'System Administrator', 'admin', 'BRANCH_CREATED', 'branch', 5, NULL, NULL, NULL, '{"code":"DUR","name":"Durg Steel Division","state":"Chhattisgarh"}', '::1', '"2026-08-11T08:19:35.307Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (10, 1, 'System Administrator', 'admin', 'PROJECT_UPDATED', 'project', 1, NULL, NULL, NULL, '{"code":"PRJ-SPONGE-02","name":"Sponge Iron Expansion Unit 2","branch_id":2,"is_active":false}', '::1', '"2026-08-11T08:19:58.547Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (11, NULL, 'System', 'system', 'USER_LOGIN', 'user', 3, NULL, NULL, NULL, '{"role":"purchase_officer","email":"kushal@skallp.in"}', '::1', '"2026-08-11T08:20:36.614Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (12, NULL, 'System', 'system', 'USER_LOGIN', 'user', 3, NULL, NULL, NULL, '{"role":"purchase_officer","email":"kushal@skallp.in"}', '::1', '"2026-08-11T08:54:39.588Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (13, NULL, 'System', 'system', 'USER_LOGIN', 'user', 1, NULL, NULL, NULL, '{"role":"admin","email":"admin@skallp.in"}', '::1', '"2026-08-11T11:13:30.915Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (14, 1, 'System Administrator', 'admin', 'USER_CREATED', 'user', 4, NULL, NULL, NULL, '{"name":"Priti Dewangan","role":"ho_verifier","email":"preeti@skallp.in"}', '::1', '"2026-08-11T11:17:50.391Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (15, NULL, 'System', 'system', 'USER_LOGIN', 'user', 4, NULL, NULL, NULL, '{"role":"ho_verifier","email":"preeti@skallp.in"}', '::1', '"2026-08-11T11:27:49.788Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (16, NULL, 'System', 'system', 'USER_LOGIN', 'user', 1, NULL, NULL, NULL, '{"role":"admin","email":"admin@skallp.in"}', '::1', '"2026-08-13T09:07:59.778Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (17, NULL, 'System', 'system', 'USER_LOGIN', 'user', 1, NULL, NULL, NULL, '{"role":"admin","email":"admin@skallp.in"}', '::1', '"2026-08-13T09:17:13.841Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (18, NULL, 'System', 'system', 'USER_LOGIN', 'user', 3, NULL, NULL, NULL, '{"role":"purchase_officer","email":"kushal@skallp.in"}', '::1', '"2026-08-13T09:17:58.633Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (19, 3, 'Kushal Rathod', 'purchase_officer', 'VENDOR_CREATED', 'vendor', 2, NULL, NULL, NULL, '{"gstin":"22AAA2312AW12","legal_name":"Botivate Services Llp","vendor_code":"VEN-96385"}', '::1', '"2026-08-13T09:21:48.671Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (20, NULL, 'System', 'system', 'USER_LOGIN', 'user', 4, NULL, NULL, NULL, '{"role":"ho_verifier","email":"preeti@skallp.in"}', '::1', '"2026-08-13T09:33:24.337Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (21, 4, 'Priti Dewangan', 'ho_verifier', 'VENDOR_HO_VERIFIED', 'vendor', 3, NULL, NULL, NULL, '{"remarks":"ok but crosscheck bank details.","legal_name":"Test Steel Supplier Pvt Ltd","vendor_code":"VEN-TEST-426"}', '::1', '"2026-08-13T10:07:32.138Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (22, NULL, 'System', 'system', 'USER_LOGIN', 'user', 1, NULL, NULL, NULL, '{"role":"admin","email":"admin@skallp.in"}', '::1', '"2026-08-13T10:08:04.965Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (23, 1, 'System Administrator', 'admin', 'USER_CREATED', 'user', 5, NULL, NULL, NULL, '{"name":"Tuleshwar Kumar","role":"ca","email":"tulesh@skallp.in"}', '::1', '"2026-08-13T10:08:57.696Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (24, 1, 'System Administrator', 'admin', 'USER_UPDATED', 'user', 1, NULL, NULL, NULL, '{"name":"System Administrator","role":"admin","email":"admin@skallp.in"}', '::1', '"2026-08-13T10:09:12.264Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (25, NULL, 'System', 'system', 'USER_LOGIN', 'user', 5, NULL, NULL, NULL, '{"role":"ca","email":"tulesh@skallp.in"}', '::1', '"2026-08-13T10:10:00.328Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (26, 5, 'Tuleshwar Kumar', 'ca', 'VENDOR_CA_APPROVED', 'vendor', 3, NULL, NULL, NULL, '{"legal_name":"Test Steel Supplier Pvt Ltd","vendor_code":"VEN-TEST-426"}', '::1', '"2026-08-13T10:11:14.051Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (27, NULL, 'System', 'system', 'USER_LOGIN', 'user', 3, NULL, NULL, NULL, '{"role":"purchase_officer","email":"kushal@skallp.in"}', '::1', '"2026-08-13T10:27:32.821Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (28, NULL, 'System', 'system', 'USER_LOGIN', 'user', 4, NULL, NULL, NULL, '{"role":"ho_verifier","email":"preeti@skallp.in"}', '::1', '"2026-08-13T10:33:57.495Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (29, NULL, 'System', 'system', 'USER_LOGIN', 'user', 3, NULL, NULL, NULL, '{"role":"purchase_officer","email":"kushal@skallp.in"}', '::1', '"2026-08-13T10:54:57.547Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (30, 3, 'Kushal Rathod', 'purchase_officer', 'QUERY_REPLIED', 'query', 2, NULL, NULL, NULL, '{"reply":"i hav eattached new docs ","file_count":1}', '::1', '"2026-08-13T11:32:25.150Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (31, NULL, 'System', 'system', 'USER_LOGIN', 'user', 5, NULL, NULL, NULL, '{"role":"ca","email":"tulesh@skallp.in"}', '::1', '"2026-08-13T11:38:55.986Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (32, NULL, 'System', 'system', 'USER_LOGIN', 'user', 3, NULL, NULL, NULL, '{"role":"purchase_officer","email":"kushal@skallp.in"}', '::1', '"2026-08-13T11:48:17.898Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (33, 3, 'Kushal Rathod', 'purchase_officer', 'PAYMENT_REQUEST_RAISED', 'payment_request', 2, 'RAI/26-27/TEST125', 'ho_approved', 'awaiting_ho_verification', '{"priority":"urgent","requested_amount":177000}', '::1', '"2026-08-13T11:48:48.676Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (34, NULL, 'System', 'system', 'USER_LOGIN', 'user', 5, NULL, NULL, NULL, '{"role":"ca","email":"tulesh@skallp.in"}', '::1', '"2026-08-13T11:49:14.403Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (35, NULL, 'System', 'system', 'USER_LOGIN', 'user', 3, NULL, NULL, NULL, '{"role":"purchase_officer","email":"kushal@skallp.in"}', '::1', '"2026-08-13T12:14:05.216Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (36, 3, 'Kushal Rathod', 'purchase_officer', 'BILL_UPLOADED', 'bill', 4, 'KAN/26-27/838084', NULL, 'bill_received', '{"invoice_number":"ertyuio","net_bill_amount":1620}', '::1', '"2026-08-13T12:19:15.728Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (37, NULL, 'System', 'system', 'USER_LOGIN', 'user', 4, NULL, NULL, NULL, '{"role":"ho_verifier","email":"preeti@skallp.in"}', '::1', '"2026-08-13T12:20:04.001Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (38, 4, 'Priti Dewangan', 'ho_verifier', 'HO_VERIFIED', 'bill', 4, 'KAN/26-27/838084', 'bill_received', 'ho_approved', '{"notes":"Supporting documents (PO, Invoice, Challan) verified with gate entry. Approved for payment request.","verified_amount":1500}', '::1', '"2026-08-14T05:14:56.331Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (39, NULL, 'System', 'system', 'USER_LOGIN', 'user', 1, NULL, NULL, NULL, '{"role":"admin","email":"admin@skallp.in"}', '::1', '"2026-08-14T05:18:03.219Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (40, NULL, 'System', 'system', 'USER_LOGIN', 'user', 5, NULL, NULL, NULL, '{"role":"ca","email":"tulesh@skallp.in"}', '::1', '"2026-08-14T05:18:30.889Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (41, NULL, 'System', 'system', 'USER_LOGIN', 'user', 3, NULL, NULL, NULL, '{"role":"purchase_officer","email":"kushal@skallp.in"}', '::1', '"2026-08-14T05:20:00.877Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (42, 3, 'Kushal Rathod', 'purchase_officer', 'PAYMENT_REQUEST_RAISED_DIRECT_TO_CA', 'payment_request', 4, 'KAN/26-27/838084', 'ho_approved', 'payment_requested_to_ca', '{"priority":"urgent","direct_to_ca":true,"requested_amount":1620}', '::1', '"2026-08-14T05:21:06.214Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (43, 3, 'Kushal Rathod', 'purchase_officer', 'PAYMENT_REQUEST_RAISED_DIRECT_TO_CA', 'payment_request', 5, 'RAI/26-27/998811', 'ho_approved', 'payment_requested_to_ca', '{"priority":"critical","direct_to_ca":true,"requested_amount":118000}', '::1', '"2026-08-14T05:21:21.487Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (44, NULL, 'System', 'system', 'USER_LOGIN', 'user', 5, NULL, NULL, NULL, '{"role":"ca","email":"tulesh@skallp.in"}', '::1', '"2026-08-14T05:24:34.830Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (45, 5, 'Tuleshwar Kumar', 'ca', 'PAYMENT_PROCESSED_FULL', 'payment', 4, 'RAI/26-27/998811', 'payment_requested_to_ca', 'paid', '{"utr":"ERTFYGBHUNJIMK","payment_mode":"Cheque","payment_amount":118000,"remaining_balance":0}', '::1', '"2026-08-14T05:34:52.019Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (46, NULL, 'System', 'system', 'USER_LOGIN', 'user', 1, NULL, NULL, NULL, '{"role":"admin","email":"admin@skallp.in"}', '::1', '"2026-08-14T05:35:48.231Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (47, 5, 'Tuleshwar Kumar', 'ca', 'PAYMENT_PROCESSED_FULL', 'payment', 6, 'KAN/26-27/838084', 'paid', 'paid', '{"utr":"IMPS202608148888","bill_id":4,"payment_mode":"IMPS","payment_amount":1620,"internal_bill_id":"KAN/26-27/838084","remaining_balance":0,"paying_bank_account":"SBI - SKALLP Project Account"}', '127.0.0.1', '"2026-08-14T05:38:07.745Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (48, NULL, 'System', 'system', 'USER_LOGIN', 'user', 5, NULL, NULL, NULL, '{"role":"ca","email":"tulesh@skallp.in"}', '::1', '"2026-08-14T05:53:12.999Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (49, NULL, 'System', 'system', 'USER_LOGIN', 'user', 3, NULL, NULL, NULL, '{"role":"purchase_officer","email":"kushal@skallp.in"}', '::1', '"2026-08-14T05:54:28.276Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (50, 3, 'Kushal Rathod', 'purchase_officer', 'VENDOR_CREATED', 'vendor', 5, NULL, NULL, NULL, '{"gstin":"MMMAAALLL001","legal_name":"Zora The Mall","vendor_code":"VEN-47155"}', '::1', '"2026-08-14T06:11:10.633Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (51, NULL, 'System', 'system', 'USER_LOGIN', 'user', 4, NULL, NULL, NULL, '{"role":"ho_verifier","email":"preeti@skallp.in"}', '::1', '"2026-08-14T06:12:06.282Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (52, NULL, 'System', 'system', 'USER_LOGIN', 'user', 5, NULL, NULL, NULL, '{"role":"ca","email":"tulesh@skallp.in"}', '::1', '"2026-08-14T06:12:36.130Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (53, 4, 'Priti Dewangan', 'ho_verifier', 'VENDOR_HO_VERIFIED', 'vendor', 5, NULL, NULL, NULL, '{"remarks":"all ok","legal_name":"Zora The Mall","vendor_code":"VEN-47155"}', '::1', '"2026-08-14T06:12:56.221Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (54, NULL, 'System', 'system', 'USER_LOGIN', 'user', 3, NULL, NULL, NULL, '{"role":"purchase_officer","email":"kushal@skallp.in"}', '::1', '"2026-08-14T06:13:59.104Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (55, 5, 'Tuleshwar Kumar', 'ca', 'VENDOR_CA_APPROVED', 'vendor', 5, NULL, NULL, NULL, '{"legal_name":"Zora The Mall","vendor_code":"VEN-47155"}', '::1', '"2026-08-14T06:14:22.049Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (56, 3, 'Kushal Rathod', 'purchase_officer', 'VENDOR_CREATED', 'vendor', 6, NULL, NULL, NULL, '{"gstin":"MGNT852963741","legal_name":"Magneto The Mall","vendor_code":"VEN-71042"}', '::1', '"2026-08-14T06:22:55.548Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (57, NULL, 'System', 'system', 'USER_LOGIN', 'user', 4, NULL, NULL, NULL, '{"role":"ho_verifier","email":"preeti@skallp.in"}', '::1', '"2026-08-14T06:32:01.333Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (58, 4, 'Priti Dewangan', 'ho_verifier', 'VENDOR_HO_VERIFIED', 'vendor', 6, NULL, NULL, NULL, '{"remarks":"ok","legal_name":"Magneto The Mall","vendor_code":"VEN-71042"}', '::1', '"2026-08-14T07:06:22.471Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (59, 5, 'Tuleshwar Kumar', 'ca', 'VENDOR_CA_APPROVED', 'vendor', 6, NULL, NULL, NULL, '{"legal_name":"Magneto The Mall","vendor_code":"VEN-71042"}', '::1', '"2026-08-14T07:06:56.856Z"') ON CONFLICT DO NOTHING;
INSERT INTO audit_logs (id, user_id, user_name, user_role, action, entity_type, entity_id, internal_bill_id, old_status, new_status, metadata, ip_address, created_at) VALUES (60, NULL, 'System', 'system', 'USER_LOGIN', 'user', 1, NULL, NULL, NULL, '{"role":"admin","email":"admin@skallp.in"}', '::1', '"2026-08-14T07:07:43.190Z"') ON CONFLICT DO NOTHING;

-- Data for notifications
INSERT INTO notifications (id, recipient_role, recipient_user_id, title, message, internal_bill_id, bill_id, type, is_read, created_at) VALUES (2, 'admin', NULL, 'System Setup Verified', 'Role-scoped notification system initialized successfully.', NULL, NULL, 'info', true, '"2026-08-11T07:15:25.058Z"') ON CONFLICT DO NOTHING;
INSERT INTO notifications (id, recipient_role, recipient_user_id, title, message, internal_bill_id, bill_id, type, is_read, created_at) VALUES (3, 'admin', NULL, 'New User Account Created', 'User account ''Priti Dewangan'' (preeti@skallp.in) was created with role ''HO VERIFIER''.', NULL, NULL, 'user_created', true, '"2026-08-11T11:17:50.426Z"') ON CONFLICT DO NOTHING;
INSERT INTO notifications (id, recipient_role, recipient_user_id, title, message, internal_bill_id, bill_id, type, is_read, created_at) VALUES (4, 'ho_verifier', NULL, 'New Vendor Registration Pending HO Verification', 'Test Vendor registered by Purchase Officer. Pending HO Verification.', NULL, NULL, 'vendor_created', true, '"2026-08-13T09:39:52.111Z"') ON CONFLICT DO NOTHING;
INSERT INTO notifications (id, recipient_role, recipient_user_id, title, message, internal_bill_id, bill_id, type, is_read, created_at) VALUES (5, 'ca', NULL, 'Vendor Verified by HO – Pending CA Approval', 'Vendor ''Test Steel Supplier Pvt Ltd'' (VEN-TEST-426) verified by HO with remarks: "ok but crosscheck bank details.". Pending CA final approval.', NULL, NULL, 'vendor_ho_verified', true, '"2026-08-13T10:07:32.219Z"') ON CONFLICT DO NOTHING;
INSERT INTO notifications (id, recipient_role, recipient_user_id, title, message, internal_bill_id, bill_id, type, is_read, created_at) VALUES (6, 'admin', NULL, 'New User Account Created', 'User account ''Tuleshwar Kumar'' (tulesh@skallp.in) was created with role ''CA''.', NULL, NULL, 'user_created', true, '"2026-08-13T10:08:57.742Z"') ON CONFLICT DO NOTHING;
INSERT INTO notifications (id, recipient_role, recipient_user_id, title, message, internal_bill_id, bill_id, type, is_read, created_at) VALUES (7, 'admin', NULL, 'User Profile Updated', 'Profile details for user account ''System Administrator'' (admin@skallp.in) were updated.', NULL, NULL, 'user_updated', true, '"2026-08-13T10:09:12.310Z"') ON CONFLICT DO NOTHING;
INSERT INTO notifications (id, recipient_role, recipient_user_id, title, message, internal_bill_id, bill_id, type, is_read, created_at) VALUES (8, 'purchase_officer', NULL, 'Vendor Approved by Payment Authority', 'Vendor ''Test Steel Supplier Pvt Ltd'' (VEN-TEST-426) approved & activated by Payment Authority. Now available in Bill Creation dropdown!', NULL, NULL, 'vendor_approved', true, '"2026-08-13T10:11:14.232Z"') ON CONFLICT DO NOTHING;
INSERT INTO notifications (id, recipient_role, recipient_user_id, title, message, internal_bill_id, bill_id, type, is_read, created_at) VALUES (9, 'ho_verifier', NULL, 'Query Response Submitted', 'Branch officer replied to query on bill: "i hav eattached new docs ...". Bill ready for re-verification.', NULL, 2, 'query_replied', true, '"2026-08-13T11:32:25.358Z"') ON CONFLICT DO NOTHING;
INSERT INTO notifications (id, recipient_role, recipient_user_id, title, message, internal_bill_id, bill_id, type, is_read, created_at) VALUES (10, 'ho_verifier', NULL, 'New Payment Request: RAI/26-27/TEST125', 'Payment request of ₹1,77,000 raised for Test Steel. Priority: URGENT.', 'RAI/26-27/TEST125', 2, 'submitted', true, '"2026-08-13T11:48:48.868Z"') ON CONFLICT DO NOTHING;
INSERT INTO notifications (id, recipient_role, recipient_user_id, title, message, internal_bill_id, bill_id, type, is_read, created_at) VALUES (11, 'ho_verifier', NULL, 'New Bill Uploaded: KAN/26-27/838084', 'Purchase Officer uploaded bill #ertyuio for ₹1,620. Pending HO document verification.', 'KAN/26-27/838084', 4, 'submitted', true, '"2026-08-13T12:19:15.871Z"') ON CONFLICT DO NOTHING;
INSERT INTO notifications (id, recipient_role, recipient_user_id, title, message, internal_bill_id, bill_id, type, is_read, created_at) VALUES (12, 'ca', NULL, 'Bill Verified & Approved by HO: RAI/26-27/998811', 'HO Verifier approved bill for payment release to CA. Amount: ₹1,18,000.', 'RAI/26-27/998811', 3, 'verified', true, '"2026-08-13T12:27:24.228Z"') ON CONFLICT DO NOTHING;
INSERT INTO notifications (id, recipient_role, recipient_user_id, title, message, internal_bill_id, bill_id, type, is_read, created_at) VALUES (13, 'ca', NULL, 'Bill Verified & Approved by HO: KAN/26-27/838084', 'HO Verifier approved bill for payment release to CA. Amount: ₹1,500.', 'KAN/26-27/838084', 4, 'verified', true, '"2026-08-14T05:14:56.560Z"') ON CONFLICT DO NOTHING;
INSERT INTO notifications (id, recipient_role, recipient_user_id, title, message, internal_bill_id, bill_id, type, is_read, created_at) VALUES (14, 'ca', NULL, 'Direct Payment Request for CA: KAN/26-27/838084', 'Purchase Officer requested ₹1,620 for HO-Approved bill ''KAN/26-27/838084''. Ready for disbursement & UTR release!', 'KAN/26-27/838084', 4, 'submitted', true, '"2026-08-14T05:21:06.387Z"') ON CONFLICT DO NOTHING;
INSERT INTO notifications (id, recipient_role, recipient_user_id, title, message, internal_bill_id, bill_id, type, is_read, created_at) VALUES (15, 'ca', NULL, 'Direct Payment Request for CA: RAI/26-27/998811', 'Purchase Officer requested ₹1,18,000 for HO-Approved bill ''RAI/26-27/998811''. Ready for disbursement & UTR release!', 'RAI/26-27/998811', 3, 'submitted', true, '"2026-08-14T05:21:21.672Z"') ON CONFLICT DO NOTHING;
INSERT INTO notifications (id, recipient_role, recipient_user_id, title, message, internal_bill_id, bill_id, type, is_read, created_at) VALUES (16, 'purchase_officer', 3, 'Payment Released: ₹1,18,000 for RAI/26-27/998811', 'CA released payment via Cheque (UTR: ERTFYGBHUNJIMK). Remaining balance: ₹0.', 'RAI/26-27/998811', 3, 'payment_made', true, '"2026-08-14T05:34:52.224Z"') ON CONFLICT DO NOTHING;
INSERT INTO notifications (id, recipient_role, recipient_user_id, title, message, internal_bill_id, bill_id, type, is_read, created_at) VALUES (17, 'purchase_officer', 3, 'Payment Released: ₹1,620 for KAN/26-27/838084', 'CA released payment via IMPS (UTR: IMPS202608149999). Remaining balance: ₹0.', 'KAN/26-27/838084', 4, 'payment_made', true, '"2026-08-14T05:37:51.837Z"') ON CONFLICT DO NOTHING;
INSERT INTO notifications (id, recipient_role, recipient_user_id, title, message, internal_bill_id, bill_id, type, is_read, created_at) VALUES (18, 'purchase_officer', 3, 'Payment Released: ₹1,620 for KAN/26-27/838084', 'CA released payment via IMPS (UTR: IMPS202608148888). Remaining balance: ₹0.', 'KAN/26-27/838084', 4, 'payment_made', true, '"2026-08-14T05:38:07.796Z"') ON CONFLICT DO NOTHING;
INSERT INTO notifications (id, recipient_role, recipient_user_id, title, message, internal_bill_id, bill_id, type, is_read, created_at) VALUES (20, 'ca', NULL, 'Vendor Verified by HO – Pending CA Approval', 'Vendor ''Zora The Mall'' (VEN-47155) verified by HO with remarks: "all ok". Pending CA final approval.', NULL, NULL, 'vendor_ho_verified', false, '"2026-08-14T06:12:56.276Z"') ON CONFLICT DO NOTHING;
INSERT INTO notifications (id, recipient_role, recipient_user_id, title, message, internal_bill_id, bill_id, type, is_read, created_at) VALUES (21, 'purchase_officer', NULL, 'Vendor Approved by Payment Authority', 'Vendor ''Zora The Mall'' (VEN-47155) approved & activated by Payment Authority. Now available in Bill Creation dropdown!', NULL, NULL, 'vendor_approved', true, '"2026-08-14T06:14:22.099Z"') ON CONFLICT DO NOTHING;
INSERT INTO notifications (id, recipient_role, recipient_user_id, title, message, internal_bill_id, bill_id, type, is_read, created_at) VALUES (19, 'ho_verifier', NULL, 'New Vendor Registration Pending HO Verification', 'New vendor ''Zora The Mall'' (VEN-47155) submitted by Purchase Officer. Pending HO Verification.', NULL, NULL, 'vendor_created', true, '"2026-08-14T06:11:10.801Z"') ON CONFLICT DO NOTHING;
INSERT INTO notifications (id, recipient_role, recipient_user_id, title, message, internal_bill_id, bill_id, type, is_read, created_at) VALUES (22, 'ho_verifier', NULL, 'New Vendor Registration Pending HO Verification', 'New vendor ''Magneto The Mall'' (VEN-71042) submitted by Purchase Officer. Pending HO Verification.', NULL, NULL, 'vendor_created', true, '"2026-08-14T06:22:55.599Z"') ON CONFLICT DO NOTHING;
INSERT INTO notifications (id, recipient_role, recipient_user_id, title, message, internal_bill_id, bill_id, type, is_read, created_at) VALUES (23, 'ca', NULL, 'Vendor Verified by HO – Pending CA Approval', 'Vendor ''Magneto The Mall'' (VEN-71042) verified by HO with remarks: "ok". Pending CA final approval.', NULL, NULL, 'vendor_ho_verified', false, '"2026-08-14T07:06:22.561Z"') ON CONFLICT DO NOTHING;
INSERT INTO notifications (id, recipient_role, recipient_user_id, title, message, internal_bill_id, bill_id, type, is_read, created_at) VALUES (24, 'purchase_officer', NULL, 'Vendor Approved by Payment Authority', 'Vendor ''Magneto The Mall'' (VEN-71042) approved & activated by Payment Authority. Now available in Bill Creation dropdown!', NULL, NULL, 'vendor_approved', false, '"2026-08-14T07:06:56.905Z"') ON CONFLICT DO NOTHING;

SELECT setval(pg_get_serial_sequence('branches', 'id'), COALESCE((SELECT MAX(id) FROM branches), 1), true);
SELECT setval(pg_get_serial_sequence('projects', 'id'), COALESCE((SELECT MAX(id) FROM projects), 1), true);
SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1), true);
SELECT setval(pg_get_serial_sequence('vendors', 'id'), COALESCE((SELECT MAX(id) FROM vendors), 1), true);
SELECT setval(pg_get_serial_sequence('bills', 'id'), COALESCE((SELECT MAX(id) FROM bills), 1), true);
SELECT setval(pg_get_serial_sequence('bill_documents', 'id'), COALESCE((SELECT MAX(id) FROM bill_documents), 1), true);
SELECT setval(pg_get_serial_sequence('payment_requests', 'id'), COALESCE((SELECT MAX(id) FROM payment_requests), 1), true);
SELECT setval(pg_get_serial_sequence('ho_queries', 'id'), COALESCE((SELECT MAX(id) FROM ho_queries), 1), true);
SELECT setval(pg_get_serial_sequence('payment_transactions', 'id'), COALESCE((SELECT MAX(id) FROM payment_transactions), 1), true);
SELECT setval(pg_get_serial_sequence('audit_logs', 'id'), COALESCE((SELECT MAX(id) FROM audit_logs), 1), true);
SELECT setval(pg_get_serial_sequence('notifications', 'id'), COALESCE((SELECT MAX(id) FROM notifications), 1), true);
